Entity ID in onChainEvent
in2workspace/blockchain-connector pull request #21
Opened 2023-11-28 12:50 UTC by yaniaiciin2

ADD:
· Added new fields on the onChainEvent entity
· Added new methods for extraction and anonymization purposes

CHANGE:
Moved 'extractEntityId' to utils because more than one service uses it

2023-11-28 13:01 UTC, oriolcanadesin2 requested changes

2023-11-28 13:01 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchainconnector/service/impl/BlockchainEventPublicationServiceImpl.java
> +                            .entityId(Utils.extractEntityId(onChainEvent.dataLocation()))
Why Utils? This is a function related to BlockchainEventPublication. Any other Service will use it.

2023-11-28 13:01 UTC, oriolcanadesin2 commented on src/main/java/es/in2/blockchainconnector/utils/Utils.java
> +    public static String extractEntityId(String entityUrl) {
See comment above :)

2023-11-29 07:37 UTC, yaniaiciin2 commented on src/main/java/es/in2/blockchainconnector/service/impl/BlockchainEventCreationServiceImpl.java
> +                        .entityId(extractHashedEntityId(dataLocation))
Done.

2023-11-29 08:48 UTC, oriolcanadesin2 approved these changes

2023-11-29 08:48 UTC, merged